# Generated by Django 4.0.3 on 2022-03-27 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tehprime', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio/images', verbose_name='Изображение')),
                ('url', models.URLField(blank=True, verbose_name='Адрес ссылки')),
            ],
            options={
                'verbose_name': 'Вендоры',
                'verbose_name_plural': 'Вендоры',
            },
        ),
    ]
