# Generated by Django 4.0.3 on 2022-03-27 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tehprime', '0002_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postavki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('sub_title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('description', models.CharField(max_length=250, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='Postavki/images', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Поставки',
                'verbose_name_plural': 'Поставки',
            },
        ),
    ]
