# Generated by Django 4.0.3 on 2022-03-27 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tehprime', '0003_postavki'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='имя')),
                ('email', models.EmailField(max_length=250, verbose_name='майл')),
                ('phone', models.CharField(max_length=100, verbose_name='телефон')),
                ('subject', models.CharField(max_length=100, verbose_name='сообщение')),
            ],
            options={
                'verbose_name': 'Заявки',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
