# Generated by Django 4.0.3 on 2022-03-27 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tehprime', '0005_about'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'О нас', 'verbose_name_plural': 'О нас'},
        ),
        migrations.RemoveField(
            model_name='about',
            name='image',
        ),
        migrations.RemoveField(
            model_name='postavki',
            name='image',
        ),
    ]
