# Generated by Django 3.2.9 on 2022-04-10 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tehprime', '0006_alter_about_options_remove_about_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postavki',
            name='image1',
            field=models.ImageField(default='', upload_to='postavki/images', verbose_name='Изображение1'),
        ),
        migrations.AddField(
            model_name='postavki',
            name='image2',
            field=models.ImageField(default='', upload_to='postavki/images', verbose_name='Изображение2'),
        ),
        migrations.AddField(
            model_name='postavki',
            name='image3',
            field=models.ImageField(default='', upload_to='postavki/images', verbose_name='Изображение3'),
        ),
        migrations.AddField(
            model_name='postavki',
            name='image4',
            field=models.ImageField(default='', upload_to='postavki/images', verbose_name='Изображение4'),
        ),
    ]
