# Generated by Django 3.2.9 on 2022-04-10 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tehprime', '0007_auto_20220410_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postavki',
            name='sub_title',
            field=models.CharField(max_length=100, verbose_name='Подзаголовок'),
        ),
    ]
