# Generated by Django 3.2.9 on 2022-04-10 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tehprime', '0008_alter_postavki_sub_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postavki',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
    ]
