# Generated by Django 4.0.3 on 2022-04-10 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tehprime', '0010_alter_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image1',
            field=models.ImageField(default='', upload_to='projects/images', verbose_name='Изображение1'),
        ),
        migrations.AddField(
            model_name='project',
            name='image2',
            field=models.ImageField(default='', upload_to='projects/images', verbose_name='Изображение2'),
        ),
        migrations.AddField(
            model_name='project',
            name='image3',
            field=models.ImageField(default='', upload_to='projects/images', verbose_name='Изображение3'),
        ),
        migrations.AddField(
            model_name='project',
            name='image4',
            field=models.ImageField(default='', upload_to='projects/images', verbose_name='Изображение6'),
        ),
    ]
