# Generated by Django 4.0.3 on 2022-04-10 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tehprime', '0011_project_image1_project_image2_project_image3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image5',
            field=models.ImageField(default='', upload_to='projects/images', verbose_name='Изображение5'),
        ),
        migrations.AddField(
            model_name='project',
            name='image6',
            field=models.ImageField(default='', upload_to='projects/images', verbose_name='Изображение6'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image4',
            field=models.ImageField(default='', upload_to='projects/images', verbose_name='Изображение4'),
        ),
    ]
