# Generated by Django 4.0.3 on 2022-04-10 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tehprime', '0014_remove_about_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='description',
            field=models.TextField(default='', verbose_name='Описание'),
        ),
    ]
