# Generated by Django 4.0.3 on 2022-04-10 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tehprime', '0016_cart_about_date_posted_about_image1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='image1',
            field=models.ImageField(upload_to='cart/images', verbose_name='Изображение'),
        ),
    ]
