# Generated by Django 4.0.3 on 2022-04-10 15:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tehprime', '0017_alter_about_image1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='date_posted',
        ),
        migrations.RemoveField(
            model_name='about',
            name='image1',
        ),
        migrations.AddField(
            model_name='cart',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='cart',
            name='image1',
            field=models.ImageField(default='', upload_to='cart/images', verbose_name='Изображение'),
        ),
    ]
