# Generated by Django 3.2.9 on 2022-04-11 12:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tehprime', '0018_remove_about_date_posted_remove_about_image1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='favourites',
            field=models.ManyToManyField(blank=True, default=None, to=settings.AUTH_USER_MODEL, verbose_name='favourites'),
        ),
    ]
