# Generated by Django 3.2.9 on 2022-04-11 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tehprime', '0021_auto_20220411_2345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='contact_info',
        ),
    ]
